---
# tasks file for roles/aws.remove

#===============================================================================
#  Search and record IDs
#===============================================================================
- name: Initialize an empty list for our strings
  set_fact:
    route_id: ""
    subnet_id: ""
    vpc_id: ""
    rhel_instance_ids: []
    rhel_group_id: ""
    win_instance_ids: []
    win_group_id: ""

- name: lookup running RHEL instances
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      tag:rhel: "dp-{{ workshop_prefix }}"
  register: ec2_rhel

- name: Append RHEL instances to list`
  set_fact:
    rhel_instance_ids: "{{ rhel_instance_ids }} + [ '{{ item.instance_id }}' ]"
  with_items: "{{ ec2_rhel.instances }}"

- name: lookup running Windows instances
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      tag:win: "dp-{{ workshop_prefix }}"
  register: ec2_win

- name: Append Windows instances to list`
  set_fact:
    win_instance_ids: "{{ win_instance_ids }} + [ '{{ item.instance_id }}' ]"
  with_items: "{{ ec2_win.instances }}"

- name: lookup running windows security groups
  ec2_group_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      tag:win: "dp-{{ workshop_prefix }}"
  register: ec2_win_grp

- name: Record Windows security group ID
  set_fact:
    win_group_id: "{{ ec2_win_grp.security_groups[0].group_id }}"
  when: ec2_win_grp.security_groups|length > 0

- name: lookup running rhel security groups
  ec2_group_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      tag:rhel: "dp-{{ workshop_prefix }}"
  register: ec2_rhel_grp

- name: Record RHEL security group ID
  set_fact:
    rhel_group_id: "{{ ec2_rhel_grp.security_groups[0].group_id }}"
  when: ec2_rhel_grp.security_groups|length > 0

- name: lookup running subnets
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      tag:workshop: "dp"
      tag:workshop_prefix: "{{ workshop_prefix }}"
  register: ec2_subnet

- name: Record subnet ID
  set_fact:
    subnet_id: "{{ ec2_subnet.subnets[0].subnet_id }}"
  when: ec2_subnet.subnets|length > 0

- name: lookup running vpc route tables
  ec2_vpc_route_table_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      tag:workshop: "dp"
      tag:workshop_prefix: "{{ workshop_prefix }}"
  register: ec2_route

- name: Record route table ID 
  set_fact:
    route_id: "{{ ec2_route.route_tables[0].id }}"
  when: ec2_route.route_tables|length > 0

- name: lookup running vpcs
  ec2_vpc_net_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    filters:
      tag:workshop: "dp"
      tag:workshop_prefix: "{{ workshop_prefix }}"
  register: ec2_vpc

- name: Record VPC ID
  set_fact:
    vpc_id: "{{ ec2_vpc.vpcs[0].id }}"
  when: ec2_vpc.vpcs|length > 0

#===============================================================================
#  Deprovisioning
#===============================================================================
- name: Remove Windows instances
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "dp-{{ workshop_prefix }}-key"
    group: "dp-{{ workshop_prefix }}-win-sg"
    region: "{{ region }}"
    instance_type: "{{ nodes.win.instance_type }}"
    image: "{{ nodes.win.ami_id }}"
    vpc_subnet_id: "{{ subnet_id }}"
#    vpc_subnet_id: "{{ lookup('file', '{{ vpc_subnet_path }}' ) }}"
    wait: true
    instance_ids: "{{ win_instance_ids }}"
#    instance_ids: "{{ lookup('file', '{{ vpc_win_ids_path }}' ) }}"
    state: absent
  when: nodes.win.count > 0

- name: Remove RHEL instances
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "dp-{{ workshop_prefix }}-key"
    group: "dp-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ nodes.rhel.instance_type }}"
    image: "{{ nodes.rhel.ami_id }}"
    vpc_subnet_id: "{{ subnet_id }}"
#    vpc_subnet_id: "{{ lookup('file', '{{ vpc_subnet_path }}' ) }}"
    wait: true
    instance_ids: "{{ rhel_instance_ids }}"
#    instance_ids: "{{ lookup('file', '{{ vpc_rhel_ids_path }}' ) }}"
    state: absent
  when: nodes.rhel.count > 0

- name: Delete VPC route table
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
#    vpc_id: "{{ lookup('file', '{{ vpc_id_path }}' ) }}"
    lookup: id
    route_table_id: "{{ route_id }}"
#    route_table_id: "{{ lookup('file', '{{ vpc_route_path }}' ) }}"
    state: absent

- name: Delete public subnet
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    cidr: "10.0.2.0/24"
    vpc_id: "{{ vpc_id }}"
#    vpc_id: "{{ lookup('file', '{{ vpc_id_path }}' ) }}"
    state: absent

- name: Delete Windows security group
  ec2_group:
    name: "dp-{{ workshop_prefix }}-win-sg"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    state: absent

- name: Delete RHEL security group
  ec2_group:
    name: "dp-{{ workshop_prefix }}-rhel-sg"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    state: absent

- name: Delete VPC internet gateway
  ec2_vpc_igw:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
#    vpc_id: "{{ lookup('file', '{{ vpc_id_path }}' ) }}"
    state: absent

- name: Delete VPC
  ec2_vpc_net:
    name: "dp-{{ workshop_prefix }}-vpc"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    cidr_block: "10.0.0.0/16"
    state: absent

- name: Delete key
  ec2_key:
    name: "dp-{{ workshop_prefix }}-key"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    state: absent
    
...
