---
# tasks file for roles/aws.create
#===============================================================================
#  Provisioning
#===============================================================================

#---------------------------------------------------
#  Ansible Hosts Creation
#---------------------------------------------------
- name: Template Ansible Hosts File
  template:
    dest: "{{ inventory_working_dir }}/hosts"
    src: "hosts.j2"

#---------------------------------------------------
#  WinRM templating
#---------------------------------------------------
- name: Template Windows WinRM configuration
  template:
    dest: "{{ winrm_path }}"
    src: "winrm.txt.j2"

#---------------------------------------------------
#  EC2 INI Creation
#---------------------------------------------------
- name: Template EC2 INI File
  template: dest="{{ inventory_working_dir }}/ec2.ini"  src=ec2.ini.j2

#---------------------------------------------------
#  SSH Key
#---------------------------------------------------
# - name: Check for existing key and remove
#   ec2_key:
#     name: "dp-{{ workshop_prefix }}-key"
#     aws_access_key: "{{ aws_access_key }}"
#     aws_secret_key: "{{ aws_secret_key }}"
#     region: "{{ region }}"
#     state: absent

- name: Create EC2 keypair
  ec2_key:
    name: "dp-{{ workshop_prefix }}-key"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    state: present
  register: ec2_key

- debug:
    var: ec2_key

- name: Make temporary location to run deployment
  file:
    path: "{{ deploy_working_dir }}"
    state: directory

- name: Create ssh keypair
  copy:
    content: "{{ ec2_key.key.private_key }}\n"
    dest: "{{ ssh_key_path }}"
    mode: 0400
  when: ec2_key.changed

#---------------------------------------------------
#  Create AWS objects
#---------------------------------------------------
- name: Create VPC
  ec2_vpc_net:
    name: "dp-{{ workshop_prefix }}-vpc"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    cidr_block: "10.0.0.0/16"
    dns_hostnames: yes
    dns_support: yes
    tags:
      username: "{{ local_user }}"
      workshop: "dp"
      workshop_prefix: "{{ workshop_prefix }}"
    state: present
  register: ec2_vpc

- debug:
    var: ec2_vpc

- name: Create VPC ID storage file
  copy:
    content: "{{ ec2_vpc.vpc.id }}\n"
    dest: "{{ vpc_id_path }}"
    mode: 0400
  when: ec2_vpc.changed

- name: Create VPC internet gateway
  ec2_vpc_igw:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    state: present
    tags:
      username: "{{ local_user }}"
      workshop: "dp"
      workshop_prefix: "{{ workshop_prefix }}"
  register: ec2_igw

- name: Create RHEL security group
  ec2_group:
    name: "dp-{{ workshop_prefix }}-rhel-sg"
    description: "SG for RHEL hosts"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    rules:
    - proto: "tcp"
      ports: 22
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on port 22 (SSH)"
#    - proto: tcp
#      ports: 8888
#      cidr_ip: 0.0.0.0/0
#      rule_desc: "allow all on port 8888 (wetty)"
    tags:
      username: "{{ local_user }}"
      workshop: "dp"
      workshop_prefix: "{{ workshop_prefix }}"
    state: present

- name: Create Windows security group
  ec2_group:
    name: "dp-{{ workshop_prefix }}-win-sg"
    description: "SG for Windows hosts"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    rules:
#    - proto: "tcp"
#      ports: 5985
#      cidr_ip: 0.0.0.0/0
#      rule_desc: "allow all on port 5985 (WinRM HTTP)"
    - proto: "tcp"
      ports: 5986
      cidr_ip: 0.0.0.0/0
      rule_desc: "allow all on port 5985 (WinRM HTTPS)"
    tags:
      username: "{{ local_user }}"
      workshop: "dp"
      workshop_prefix: "{{ workshop_prefix }}"
    state: present

- name: Create public subnet
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    cidr: "10.0.2.0/24"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    tags:
      username: "{{ local_user }}"
      workshop: "dp"
      workshop_prefix: "{{ workshop_prefix }}"
    wait: yes
  register: ec2_subnet

- name: Create VPC public subnet storage file
  copy:
    content: "{{ ec2_subnet.subnet.id }}\n"
    dest: "{{ vpc_subnet_path }}"
    mode: 0400
  when: ec2_subnet.changed

- name: Create VPC route table
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    subnets:
      - "{{ ec2_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ ec2_igw.gateway_id }}"
    lookup: tag
    tags:
      username: "{{ local_user }}"
      workshop: "dp"
      workshop_prefix: "{{ workshop_prefix }}"
    state: present
  register: ec2_route

- name: Create VPC route table storage file
  copy:
    content: "{{ ec2_route.route_table.route_table_id }}\n"
    dest: "{{ vpc_route_path }}"
    mode: 0400
  when: ec2_route.changed

- name: Create RHEL instances
# ansible --private-key=/home/ajacocks/Dropbox/src/dp/.redhatgov/dp-key -m ping tag_name_{{ workshop_prefix }}_dp_rhel
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    assign_public_ip: yes
    key_name: "dp-{{ workshop_prefix }}-key"
    group: "dp-{{ workshop_prefix }}-rhel-sg"
    region: "{{ region }}"
    instance_type: "{{ nodes.rhel.instance_type }}"
    image: "{{ nodes.rhel.ami_id }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}"
    wait: true
    exact_count: "{{ nodes.rhel.count }}"
    count_tag: "name"
    instance_tags:
      name: "dp-{{ workshop_prefix }}-rhel"
      username: "{{ local_user }}"
      workshop_prefix: "{{ workshop_prefix }}"
  register: ec2

- name: Create VPC RHEL instance storage file
  copy:
    content: "{{ ec2.instance_ids }}\n"
    dest: "{{ vpc_rhel_ids_path }}"
    mode: 0400
  when: ec2.changed

- name: Create Windows instances
# ansible --private-key=/home/ajacocks/Dropbox/src/dp/.redhatgov/dp-key -m ping tag_name_{{ workshop_prefix }}_dp_rhel
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    assign_public_ip: yes
    key_name: "dp-{{ workshop_prefix }}-key"
    group: "dp-{{ workshop_prefix }}-win-sg"
    region: "{{ region }}"
    instance_type: "{{ nodes.win.instance_type }}"
    image: "{{ nodes.win.ami_id }}"
    vpc_subnet_id: "{{ ec2_subnet.subnet.id }}"
    user_data: "{{ lookup('file', '{{ winrm_path }}') }}"
    wait: true
    exact_count: "{{ nodes.win.count }}"
    count_tag: "name"
    instance_tags:
      name: "dp-{{ workshop_prefix }}-win"
      username: "{{ local_user }}"
      workshop_prefix: "{{ workshop_prefix }}"
  register: ec2_win

- name: Create VPC Windows instance storage file
  copy:
    content: "{{ ec2_win.instance_ids }}\n"
    dest: "{{ vpc_win_ids_path }}"
    mode: 0400
  when: ec2_win.changed

- debug:
    var: ec2_win

#- debug:
#    var: ec2

#- debug:
#    var: ec2.instances

#- debug:
#    var: ec2.instances.{{ item }}
#  with_sequence: count="{{ nodes.rhel.count }}" start=0

#- debug:
#    var: ec2.instances.{{ item }}.public_dns_name
#  with_sequence: count="{{ nodes.rhel.count }}" start=0

#- name: Display output
#  debug:
#  debug: msg="The key is {{ item.key }} and the value is {{ item.value }}"
#  with_dict: "{{ ec2.ami_launch_index }}"
#  with_dict: "{{ ec2.ami_launch_index[0] }}"
#  with_dict: "{{ output.results[1].response[0] }}"

#- name: Create DNS records
#  route53:
#    aws_access_key: "{{ aws_access_key }}"
#    aws_secret_key: "{{ aws_secret_key }}"
#    region: "{{ region }}"
#    zone: "{{ domain_name }}"
#    type: "CNAME"
#    ttl: "300"
#    record: "{{ workshop_prefix }}.rhel.{{ item }}.dp.redhatgov.io"
#    value: "\{{ ec2.instances.\{{ item \}}.dns_name \}}"
#    value: "{{ lookup('vars', ec2.instances + '.' + item + '.' + dns_name) }}"
#    value: 
#    wait: yes
#    state: present
#  with_sequence: count={{ nodes.rhel.count }} start=0
#  with_items: ec2.ami_launch_index

...
